language: csharp
solution: HttpWebClient.sln
sudo: false

install:
  - nuget restore HttpWebClient.sln
  - nuget install xunit.runner.console -Version 2.2.0 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Debug HttpWebClient.sln
  - mono ./testrunner/xunit.runner.console.2.2.0/tools/xunit.console.exe ./HttpWebClient.UnitTests/bin/Debug/HttpWebClient.UnitTests.dll
