language: csharp
solution: HttpWebClient.sln
sudo: false

install:
  - nuget restore HttpWebClient.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Debug HttpWebClient.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./HttpWebClient.UnitTests/bin/Debug/HttpWebClient.UnitTests.dll
